version: '3.4'

networks:
  demoblazorapp:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp
  demoblazorserverapp:
    container_name: demo-blazor-app
    image: ${DOCKER_REGISTRY-}demoblazorserverapp
    build:
      context: .
      dockerfile: DemoBlazorServerApp/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp